### ISSUE TITLE
Use Python package which implements actions hooks for OpenShift 3.

### ISSUE THREAD

**Issue by GrahamDumpleton** [dbrrt/os-flask-oracle-template#1]
You would be better off using:

* https://github.com/getwarped/powershift-image

Then you don't need to carry those heavily customised ``assemble`` and ``run`` scripts. Install and use the functionality from the Python package instead. This means you inherit fixes. From memory the scripts you copied already have one bug that I haven't gone back and fixed yet, but is fixed in the Python packaged version.

**Comment by dbrrt** [comment]
@GrahamDumpleton That looks great, I didn't know there was such a package for such thing. For now, it seems to be working in our dev environement this way, but I'll update it as soon as possible with the library directly.
Thank you so much for your help, which allowed me to put this in place !
