### ISSUE TITLE
Alternate way of doing action hooks.

### ISSUE THREAD

**Issue by GrahamDumpleton** [dbrrt/os-flask-oracle-template#2]
Considering looking at:

* https://github.com/getwarped/powershift-image

as packaged up way of pulling in action hooks functionality.

**Comment by dbrrt** [comment]
@GrahamDumpleton Sorry for the delay, that's very interesting! If I understand well, this library contains embeds the scripts `assemble` and `run`, and adding it to `requirements.txt` will premit to remove `.s2i/bin` folder? I don't get how OpenShift will trigger hooks having it installed this way as a regular python package with `conda`/`pip`.

**Comment by GrahamDumpleton** [comment]
Not quite. You still have to have ``.s2i/bin/assemble`` and ``.s2i/bin/run`` scripts, but the ``assemble`` script bootstraps things by ``pip`` installing the package. So not listing in ``requirements.txt.`` The page shows the ``assemble`` and ``run`` script you use. Only a few lines each.

**Comment by dbrrt** [comment]
So do you have to create a custom Python cartridge/Dockerfile to use `powershift-image` on OpenShift? Is that a replacement for oc binaries or an extension of s2i?, to be used for python applications? It's not super obvious in the README, It deserves at least an example to showcase what it's and how it works :) . Additional hooks look really helpful!

**Comment by GrahamDumpleton** [comment]
It is exactly what you were doing already, the ``assemble`` and ``run`` scripts are just being pulled in as a Python package, with it calling them, rather than you have your own copy which you then have to maintain. No special S2I builder is required and it is not a replacement for ``oc``. The ``powershift image`` command is only for use in a running image, and not on your local computer.

You can see an example which uses it at:

* https://github.com/openshift-katacoda/blog-django-py

but that is doing a lot of other stuff as well so it may just confuse you further if the ``README`` file isn't explaining it well enough. Maybe just stick with what you have then.

**Comment by dbrrt** [comment]
Ah yes, now I see, it's way neater invoking powershift directly from assemble rather than maintaining everything in this file. I'll update this soon, thanks for notifying me that!
